// Code generated by command: go run compress.go. DO NOT EDIT.

#include "textflag.h"

DATA iv<>+0(SB)/4, $0x6a09e667
DATA iv<>+4(SB)/4, $0xbb67ae85
DATA iv<>+8(SB)/4, $0x3c6ef372
DATA iv<>+12(SB)/4, $0xa54ff53a
DATA iv<>+16(SB)/4, $0x510e527f
DATA iv<>+20(SB)/4, $0x9b05688c
DATA iv<>+24(SB)/4, $0x1f83d9ab
DATA iv<>+28(SB)/4, $0x5be0cd19
GLOBL iv<>(SB), RODATA|NOPTR, $32

DATA rot16_shuf<>+0(SB)/1, $0x02
DATA rot16_shuf<>+1(SB)/1, $0x03
DATA rot16_shuf<>+2(SB)/1, $0x00
DATA rot16_shuf<>+3(SB)/1, $0x01
DATA rot16_shuf<>+4(SB)/1, $0x06
DATA rot16_shuf<>+5(SB)/1, $0x07
DATA rot16_shuf<>+6(SB)/1, $0x04
DATA rot16_shuf<>+7(SB)/1, $0x05
DATA rot16_shuf<>+8(SB)/1, $0x0a
DATA rot16_shuf<>+9(SB)/1, $0x0b
DATA rot16_shuf<>+10(SB)/1, $0x08
DATA rot16_shuf<>+11(SB)/1, $0x09
DATA rot16_shuf<>+12(SB)/1, $0x0e
DATA rot16_shuf<>+13(SB)/1, $0x0f
DATA rot16_shuf<>+14(SB)/1, $0x0c
DATA rot16_shuf<>+15(SB)/1, $0x0d
DATA rot16_shuf<>+16(SB)/1, $0x12
DATA rot16_shuf<>+17(SB)/1, $0x13
DATA rot16_shuf<>+18(SB)/1, $0x10
DATA rot16_shuf<>+19(SB)/1, $0x11
DATA rot16_shuf<>+20(SB)/1, $0x16
DATA rot16_shuf<>+21(SB)/1, $0x17
DATA rot16_shuf<>+22(SB)/1, $0x14
DATA rot16_shuf<>+23(SB)/1, $0x15
DATA rot16_shuf<>+24(SB)/1, $0x1a
DATA rot16_shuf<>+25(SB)/1, $0x1b
DATA rot16_shuf<>+26(SB)/1, $0x18
DATA rot16_shuf<>+27(SB)/1, $0x19
DATA rot16_shuf<>+28(SB)/1, $0x1e
DATA rot16_shuf<>+29(SB)/1, $0x1f
DATA rot16_shuf<>+30(SB)/1, $0x1c
DATA rot16_shuf<>+31(SB)/1, $0x1d
GLOBL rot16_shuf<>(SB), RODATA|NOPTR, $32

DATA rot8_shuf<>+0(SB)/1, $0x01
DATA rot8_shuf<>+1(SB)/1, $0x02
DATA rot8_shuf<>+2(SB)/1, $0x03
DATA rot8_shuf<>+3(SB)/1, $0x00
DATA rot8_shuf<>+4(SB)/1, $0x05
DATA rot8_shuf<>+5(SB)/1, $0x06
DATA rot8_shuf<>+6(SB)/1, $0x07
DATA rot8_shuf<>+7(SB)/1, $0x04
DATA rot8_shuf<>+8(SB)/1, $0x09
DATA rot8_shuf<>+9(SB)/1, $0x0a
DATA rot8_shuf<>+10(SB)/1, $0x0b
DATA rot8_shuf<>+11(SB)/1, $0x08
DATA rot8_shuf<>+12(SB)/1, $0x0d
DATA rot8_shuf<>+13(SB)/1, $0x0e
DATA rot8_shuf<>+14(SB)/1, $0x0f
DATA rot8_shuf<>+15(SB)/1, $0x0c
DATA rot8_shuf<>+16(SB)/1, $0x11
DATA rot8_shuf<>+17(SB)/1, $0x12
DATA rot8_shuf<>+18(SB)/1, $0x13
DATA rot8_shuf<>+19(SB)/1, $0x10
DATA rot8_shuf<>+20(SB)/1, $0x15
DATA rot8_shuf<>+21(SB)/1, $0x16
DATA rot8_shuf<>+22(SB)/1, $0x17
DATA rot8_shuf<>+23(SB)/1, $0x14
DATA rot8_shuf<>+24(SB)/1, $0x19
DATA rot8_shuf<>+25(SB)/1, $0x1a
DATA rot8_shuf<>+26(SB)/1, $0x1b
DATA rot8_shuf<>+27(SB)/1, $0x18
DATA rot8_shuf<>+28(SB)/1, $0x1d
DATA rot8_shuf<>+29(SB)/1, $0x1e
DATA rot8_shuf<>+30(SB)/1, $0x1f
DATA rot8_shuf<>+31(SB)/1, $0x1c
GLOBL rot8_shuf<>(SB), RODATA|NOPTR, $32

// func Compress(chain *[8]uint32, block *[16]uint32, counter uint64, blen uint32, flags uint32, out *[16]uint32)
// Requires: AVX
TEXT ·Compress(SB), NOSPLIT, $0-40
	MOVQ    chain+0(FP), AX
	MOVQ    block+8(FP), CX
	MOVQ    counter+16(FP), DX
	MOVL    blen+24(FP), BX
	MOVL    flags+28(FP), SI
	MOVQ    out+32(FP), DI
	VMOVDQU (AX), X0
	VMOVDQU 16(AX), X1
	VMOVDQU iv<>+0(SB), X2
	VMOVD   DX, X3
	SHRQ    $0x20, DX
	VPINSRD $0x01, DX, X3, X3
	VPINSRD $0x02, BX, X3, X3
	VPINSRD $0x03, SI, X3, X3
	VMOVDQU (CX), X4
	VMOVDQU 16(CX), X5
	VMOVDQU 32(CX), X6
	VMOVDQU 48(CX), X7
	VMOVDQU rot16_shuf<>+0(SB), X8
	VMOVDQU rot8_shuf<>+0(SB), X9

	// round 1
	VSHUFPS $0x88, X5, X4, X10
	VPADDD  X10, X0, X0
	VPADDD  X1, X0, X0
	VPXOR   X0, X3, X3
	VPSHUFB X8, X3, X3
	VPADDD  X3, X2, X2
	VPXOR   X2, X1, X1
	VPSRLD  $0x0c, X1, X11
	VPSLLD  $0x14, X1, X1
	VPOR    X11, X1, X1
	VSHUFPS $0xdd, X5, X4, X4
	VPADDD  X4, X0, X0
	VPADDD  X1, X0, X0
	VPXOR   X0, X3, X3
	VPSHUFB X9, X3, X3
	VPADDD  X3, X2, X2
	VPXOR   X2, X1, X1
	VPSRLD  $0x07, X1, X5
	VPSLLD  $0x19, X1, X1
	VPOR    X5, X1, X1
	VPSHUFD $0x93, X0, X0
	VPSHUFD $0x4e, X3, X3
	VPSHUFD $0x39, X2, X2
	VSHUFPS $0x88, X7, X6, X5
	VSHUFPS $0x93, X5, X5, X5
	VPADDD  X5, X0, X0
	VPADDD  X1, X0, X0
	VPXOR   X0, X3, X3
	VPSHUFB X8, X3, X3
	VPADDD  X3, X2, X2
	VPXOR   X2, X1, X1
	VPSRLD  $0x0c, X1, X11
	VPSLLD  $0x14, X1, X1
	VPOR    X11, X1, X1
	VSHUFPS $0xdd, X7, X6, X6
	VSHUFPS $0x93, X6, X6, X6
	VPADDD  X6, X0, X0
	VPADDD  X1, X0, X0
	VPXOR   X0, X3, X3
	VPSHUFB X9, X3, X3
	VPADDD  X3, X2, X2
	VPXOR   X2, X1, X1
	VPSRLD  $0x07, X1, X7
	VPSLLD  $0x19, X1, X1
	VPOR    X7, X1, X1
	VPSHUFD $0x39, X0, X0
	VPSHUFD $0x4e, X3, X3
	VPSHUFD $0x93, X2, X2

	// round 2
	VSHUFPS    $0xd6, X4, X10, X7
	VSHUFPS    $0x39, X7, X7, X7
	VPADDD     X7, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X11
	VPSLLD     $0x14, X1, X1
	VPOR       X11, X1, X1
	VSHUFPS    $0xfa, X6, X5, X11
	VPSHUFD    $0x0f, X10, X10
	VPBLENDW   $0x33, X10, X11, X11
	VPADDD     X11, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X10
	VPSLLD     $0x19, X1, X1
	VPOR       X10, X1, X1
	VPSHUFD    $0x93, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x39, X2, X2
	VPUNPCKLDQ X4, X6, X12
	VPBLENDW   $0xc0, X5, X12, X12
	VSHUFPS    $0xb4, X12, X12, X12
	VPADDD     X12, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X10
	VPSLLD     $0x14, X1, X1
	VPOR       X10, X1, X1
	VPUNPCKHDQ X6, X4, X10
	VPUNPCKLDQ X10, X5, X4
	VSHUFPS    $0x1e, X4, X4, X4
	VPADDD     X4, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X5
	VPSLLD     $0x19, X1, X1
	VPOR       X5, X1, X1
	VPSHUFD    $0x39, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x93, X2, X2

	// round 3
	VSHUFPS    $0xd6, X11, X7, X5
	VSHUFPS    $0x39, X5, X5, X5
	VPADDD     X5, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X6
	VPSLLD     $0x14, X1, X1
	VPOR       X6, X1, X1
	VSHUFPS    $0xfa, X4, X12, X6
	VPSHUFD    $0x0f, X7, X7
	VPBLENDW   $0x33, X7, X6, X6
	VPADDD     X6, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X7
	VPSLLD     $0x19, X1, X1
	VPOR       X7, X1, X1
	VPSHUFD    $0x93, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x39, X2, X2
	VPUNPCKLDQ X11, X4, X10
	VPBLENDW   $0xc0, X12, X10, X10
	VSHUFPS    $0xb4, X10, X10, X10
	VPADDD     X10, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X7
	VPSLLD     $0x14, X1, X1
	VPOR       X7, X1, X1
	VPUNPCKHDQ X4, X11, X7
	VPUNPCKLDQ X7, X12, X4
	VSHUFPS    $0x1e, X4, X4, X4
	VPADDD     X4, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X7
	VPSLLD     $0x19, X1, X1
	VPOR       X7, X1, X1
	VPSHUFD    $0x39, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x93, X2, X2

	// round 4
	VSHUFPS    $0xd6, X6, X5, X7
	VSHUFPS    $0x39, X7, X7, X7
	VPADDD     X7, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X11
	VPSLLD     $0x14, X1, X1
	VPOR       X11, X1, X1
	VSHUFPS    $0xfa, X4, X10, X11
	VPSHUFD    $0x0f, X5, X5
	VPBLENDW   $0x33, X5, X11, X11
	VPADDD     X11, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X5
	VPSLLD     $0x19, X1, X1
	VPOR       X5, X1, X1
	VPSHUFD    $0x93, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x39, X2, X2
	VPUNPCKLDQ X6, X4, X12
	VPBLENDW   $0xc0, X10, X12, X12
	VSHUFPS    $0xb4, X12, X12, X12
	VPADDD     X12, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X5
	VPSLLD     $0x14, X1, X1
	VPOR       X5, X1, X1
	VPUNPCKHDQ X4, X6, X5
	VPUNPCKLDQ X5, X10, X4
	VSHUFPS    $0x1e, X4, X4, X4
	VPADDD     X4, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X5
	VPSLLD     $0x19, X1, X1
	VPOR       X5, X1, X1
	VPSHUFD    $0x39, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x93, X2, X2

	// round 5
	VSHUFPS    $0xd6, X11, X7, X5
	VSHUFPS    $0x39, X5, X5, X5
	VPADDD     X5, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X6
	VPSLLD     $0x14, X1, X1
	VPOR       X6, X1, X1
	VSHUFPS    $0xfa, X4, X12, X6
	VPSHUFD    $0x0f, X7, X7
	VPBLENDW   $0x33, X7, X6, X6
	VPADDD     X6, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X7
	VPSLLD     $0x19, X1, X1
	VPOR       X7, X1, X1
	VPSHUFD    $0x93, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x39, X2, X2
	VPUNPCKLDQ X11, X4, X10
	VPBLENDW   $0xc0, X12, X10, X10
	VSHUFPS    $0xb4, X10, X10, X10
	VPADDD     X10, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X7
	VPSLLD     $0x14, X1, X1
	VPOR       X7, X1, X1
	VPUNPCKHDQ X4, X11, X7
	VPUNPCKLDQ X7, X12, X4
	VSHUFPS    $0x1e, X4, X4, X4
	VPADDD     X4, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X7
	VPSLLD     $0x19, X1, X1
	VPOR       X7, X1, X1
	VPSHUFD    $0x39, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x93, X2, X2

	// round 6
	VSHUFPS    $0xd6, X6, X5, X7
	VSHUFPS    $0x39, X7, X7, X7
	VPADDD     X7, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X11
	VPSLLD     $0x14, X1, X1
	VPOR       X11, X1, X1
	VSHUFPS    $0xfa, X4, X10, X11
	VPSHUFD    $0x0f, X5, X5
	VPBLENDW   $0x33, X5, X11, X11
	VPADDD     X11, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X5
	VPSLLD     $0x19, X1, X1
	VPOR       X5, X1, X1
	VPSHUFD    $0x93, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x39, X2, X2
	VPUNPCKLDQ X6, X4, X12
	VPBLENDW   $0xc0, X10, X12, X12
	VSHUFPS    $0xb4, X12, X12, X12
	VPADDD     X12, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X5
	VPSLLD     $0x14, X1, X1
	VPOR       X5, X1, X1
	VPUNPCKHDQ X4, X6, X5
	VPUNPCKLDQ X5, X10, X4
	VSHUFPS    $0x1e, X4, X4, X4
	VPADDD     X4, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X5
	VPSLLD     $0x19, X1, X1
	VPOR       X5, X1, X1
	VPSHUFD    $0x39, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x93, X2, X2

	// round 7
	VSHUFPS    $0xd6, X11, X7, X5
	VSHUFPS    $0x39, X5, X5, X5
	VPADDD     X5, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X5
	VPSLLD     $0x14, X1, X1
	VPOR       X5, X1, X1
	VSHUFPS    $0xfa, X4, X12, X5
	VPSHUFD    $0x0f, X7, X6
	VPBLENDW   $0x33, X6, X5, X5
	VPADDD     X5, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X5
	VPSLLD     $0x19, X1, X1
	VPOR       X5, X1, X1
	VPSHUFD    $0x93, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x39, X2, X2
	VPUNPCKLDQ X11, X4, X5
	VPBLENDW   $0xc0, X12, X5, X5
	VSHUFPS    $0xb4, X5, X5, X5
	VPADDD     X5, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X8, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x0c, X1, X5
	VPSLLD     $0x14, X1, X1
	VPOR       X5, X1, X1
	VPUNPCKHDQ X4, X11, X6
	VPUNPCKLDQ X6, X12, X4
	VSHUFPS    $0x1e, X4, X4, X4
	VPADDD     X4, X0, X0
	VPADDD     X1, X0, X0
	VPXOR      X0, X3, X3
	VPSHUFB    X9, X3, X3
	VPADDD     X3, X2, X2
	VPXOR      X2, X1, X1
	VPSRLD     $0x07, X1, X4
	VPSLLD     $0x19, X1, X1
	VPOR       X4, X1, X1
	VPSHUFD    $0x39, X0, X0
	VPSHUFD    $0x4e, X3, X3
	VPSHUFD    $0x93, X2, X2

	// finalize
	VPXOR   X2, X0, X0
	VPXOR   X3, X1, X1
	VPXOR   (AX), X2, X2
	VPXOR   16(AX), X3, X3
	VMOVDQU X0, (DI)
	VMOVDQU X1, 16(DI)
	VMOVDQU X2, 32(DI)
	VMOVDQU X3, 48(DI)
	RET
