// Generates the arm64 single block compression function.
//
// This one is scalar. The four G calls of a half round touch disjoint state
// words, so a wide core runs them in parallel, and on arm64 that beats holding
// the state in one vector: the four lanes would be spending the same
// parallelism the scalar form already has, and they would add the
// diagonalization and the message permutation on top. Measured on Graviton5, a
// NEON version of this function runs at half the speed of the scalar C one.
//
// What the compiler leaves on the table is the schedule. Go emits the four G
// calls one after another, so every instruction waits on the one before it;
// gcc interleaves them and reaches a much higher IPC on the same instruction
// count. Here the four are interleaved by construction, and all sixteen state
// words stay in registers for the whole function.
package main

import (
	"bufio"
	"fmt"
	"os"
)

var iv = [4]uint32{0x6A09E667, 0xBB67AE85, 0x3C6EF372, 0xA54FF53A}

// The state words each of the four G calls of a half round works on. The
// column round takes columns and the diagonal round takes diagonals, which is
// why the second table is skewed.
var halves = [2][4][4]int{
	{{0, 4, 8, 12}, {1, 5, 9, 13}, {2, 6, 10, 14}, {3, 7, 11, 15}},
	{{0, 5, 10, 15}, {1, 6, 11, 12}, {2, 7, 8, 13}, {3, 4, 9, 14}},
}

var schedule = [7][16]int{
	{0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15},
	{2, 6, 3, 10, 7, 0, 4, 13, 1, 11, 12, 5, 9, 14, 15, 8},
	{3, 4, 10, 12, 13, 2, 7, 14, 6, 5, 9, 0, 11, 15, 8, 1},
	{10, 7, 12, 9, 14, 3, 13, 15, 4, 0, 11, 2, 5, 8, 1, 6},
	{12, 13, 9, 11, 15, 10, 14, 8, 7, 2, 5, 3, 0, 1, 6, 4},
	{9, 14, 11, 5, 8, 12, 15, 1, 13, 3, 0, 10, 2, 6, 4, 7},
	{11, 15, 5, 0, 1, 9, 8, 6, 14, 10, 2, 12, 3, 4, 7, 13},
}

// R0..R15 hold the state for the whole function; R18 is the platform register
// and R27..R30 belong to the assembler and the runtime, which leaves plenty.
const (
	block = 16 // the block pointer, for the message loads
	out   = 17 // the output pointer, only touched at the end
	chain = 19 // the chaining value pointer, reloaded for the feed forward
	msg   = 20 // R20..R23, one message word per G call of the half round
)

func main() {
	w := bufio.NewWriter(os.Stdout)
	a := &asm{w: w}

	a.line("// Code generated by command: go run ./compress/compress_arm64. DO NOT EDIT.")
	a.line("")
	a.line("#include \"textflag.h\"")
	a.line("")
	emitData(a)
	emitCompress(a, "Compress", true)
	a.line("")
	emitCompress(a, "CompressBaseline", false)

	if a.err == nil {
		a.err = w.Flush()
	}
	if a.err != nil {
		fmt.Fprintln(os.Stderr, a.err)
		os.Exit(1)
	}
}

// emitData holds the second half of the IV. Materializing those four words as
// immediates costs two instructions each on arm64; loading them costs two in
// total.
func emitData(a *asm) {
	for i, v := range iv {
		a.op("DATA iv<>+%d(SB)/4, $0x%08x", 4*i, v)
	}
	a.op("GLOBL iv<>(SB), RODATA|NOPTR, $16")
	a.line("")
}

// emitCompress writes one copy of the function. messageFirst picks which of
// the two adds feeding the first row goes in front; taking the second row last
// leaves one fewer instruction between the rotate that produced that row and
// the xor that consumes this one.
func emitCompress(a *asm, name string, messageFirst bool) {
	a.line("// func %s(chain *[8]uint32, block *[16]uint32, counter uint64, blen uint32, flags uint32, out *[16]uint32)", name)
	a.line("TEXT ·%s(SB), NOSPLIT|NOFRAME, $0-40", name)
	a.op("MOVD chain+0(FP), R%d", chain)
	a.op("MOVD block+8(FP), R%d", block)
	a.op("MOVD counter+16(FP), R24")
	a.op("MOVD out+32(FP), R%d", out)
	a.line("")

	a.comment("rows 0 and 1 are the chaining value, row 2 is the IV, row 3 is")
	a.comment("the counter, the block length and the flags")
	for i := 0; i < 8; i += 2 {
		a.op("LDPW %d(R%d), (R%d, R%d)", 4*i, chain, i, i+1)
	}
	a.op("MOVD $iv<>(SB), R25")
	a.op("LDPW 0(R25), (R8, R9)")
	a.op("LDPW 8(R25), (R10, R11)")
	a.op("MOVD R24, R12")
	a.op("LSR $32, R24, R13")
	a.op("MOVWU blen+24(FP), R14")
	a.op("MOVWU flags+28(FP), R15")
	a.line("")

	for round := 0; round < 7; round++ {
		for half := 0; half < 2; half++ {
			a.comment("round %d, %s", round+1, []string{"columns", "diagonals"}[half])
			emitHalf(a, halves[half], schedule[round][8*half:8*half+8], messageFirst)
			a.line("")
		}
	}

	a.comment("the two halves of the state fold together, and the second half")
	a.comment("also folds back into the chaining value")
	for i := 0; i < 8; i += 2 {
		a.op("LDPW %d(R%d), (R24, R25)", 4*i, chain)
		a.op("EORW R24, R%d, R24", 8+i)
		a.op("EORW R25, R%d, R25", 8+i+1)
		a.op("STPW (R24, R25), %d(R%d)", 4*(8+i), out)
		a.op("EORW R%d, R%d, R%d", 8+i, i, i)
		a.op("EORW R%d, R%d, R%d", 8+i+1, i+1, i+1)
	}
	for i := 0; i < 8; i += 2 {
		a.op("STPW (R%d, R%d), %d(R%d)", i, i+1, 4*i, out)
	}
	a.op("RET")
}

// emitHalf writes the four G calls of one half round interleaved: every step
// runs for all four before the next one starts, so each instruction sits four
// away from the one it depends on.
func emitHalf(a *asm, quads [4][4]int, sched []int, messageFirst bool) {
	// mix is half of a G: the first row takes a message word and the second
	// row, then two xor-and-rotate pairs run down the other two rows.
	mix := func(off, rotD, rotB int) {
		for i := range quads {
			a.op("MOVWU %d(R%d), R%d", 4*sched[2*i+off], block, msg+i)
		}
		addMessage := func() {
			for i, q := range quads {
				a.op("ADDW R%d, R%d, R%d", msg+i, q[0], q[0])
			}
		}
		addRow := func() {
			for _, q := range quads {
				a.op("ADDW R%d, R%d, R%d", q[1], q[0], q[0])
			}
		}
		if messageFirst {
			addMessage()
			addRow()
		} else {
			addRow()
			addMessage()
		}
		for _, q := range quads {
			a.op("EORW R%d, R%d, R%d", q[0], q[3], q[3])
		}
		for _, q := range quads {
			a.op("RORW $%d, R%d, R%d", rotD, q[3], q[3])
		}
		for _, q := range quads {
			a.op("ADDW R%d, R%d, R%d", q[3], q[2], q[2])
		}
		for _, q := range quads {
			a.op("EORW R%d, R%d, R%d", q[2], q[1], q[1])
		}
		for _, q := range quads {
			a.op("RORW $%d, R%d, R%d", rotB, q[1], q[1])
		}
	}
	mix(0, 16, 12)
	mix(1, 8, 7)
}
